export const responsive = {
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 4,
    slidesToSlide: 1,
  },
  tablet: {
    breakpoint: { max: 1024, min: 780 },
    items: 3,
    slidesToSlide: 1,
  },
  mobile: {
    breakpoint: { max: 780, min: 464 },
    items: 2,
    slidesToSlide: 1,
  },
};

export const responsiveLandingPanel = {
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 1,
  },
  tablet: {
    breakpoint: { max: 1024, min: 464 },
    items: 1,
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1,
  },
};

export const landingPanel = [
  {
    id: 1,
    image:
      "https://corso.md/public/slider/thumbs/version_1280x540x1280x540x1/e95c96408cbe7c4aadc93a5a123c9d6b.png",
  },
  {
    id: 2,
    image:
      "https://corso.md/public/slider/thumbs/version_1280x540x1280x540x1/295edd123e75d8e07e2b144e2c059106.jpg",
  },
];
export const durlestiStreat = [
  { label: "Strada Ștefan-Vodă" },
  { label: "Strada Boris Glavan" },
  { label: "Strada Nicolae Milescu Spătarul" },
  { label: "Strada Viilor" },
  { label: "Strada Vasile Alecsandri" },
  { label: "Strada Mihai Viteazul" },
  { label: "Strada Nicolae Gribov" },
  { label: "Strada Dimitrie Cantemir" },
  { label: "Strada Nicolae Dimo" },
  { label: "Strada Vasile Lupu" },
  { label: "Strada Mihai Eminescu" },
  { label: "Strada Constantin Brâncoveanu" },
  { label: "Strada Căpriana" },
  { label: "Strada Ion Creangă" },
  { label: "Strada Ion Soltîs" },
  { label: "Strada Tudor Vladimirescu" },
  { label: "Strada Caucaz" },
  { label: "Strada Gheorghe Asachi" },
  { label: "Strada Răzeșilor" },
  { label: "Strada Cartușa" },
  { label: "Strada Alexandru Marinescu" },
  { label: "Strada George Coșbuc" },
  { label: "Strada Codrilor" },
  { label: "Strada Mitropolit Dosoftei" },
  { label: "Strada Haiducul Tobultoc" },
  { label: "Strada Petru Rareș" },
  { label: "Strada Izvoarelor" },
  { label: "Strada Burebista" },
  { label: "Strada Dacilor" },
  { label: "Strada 27 August 1989" },
  { label: "Strada Petru Movilă" },
  { label: "Strada Șoimilor" },
  { label: "Strada Liviu Damian" },
  { label: "Strada Ialoveni" },
  { label: "Strada Sfîntul Gheorghe" },
  { label: "Strada Rediul Mare" },
  { label: "Strada Rediul Mic" },
  { label: "Strada Hotin" },
  { label: "Strada Livezilor" },
  { label: "Strada Gavriil Musicescu" },
  { label: "Strada Miron Costin" },
  { label: "Strada Cișmelelor" },
  { label: "Strada Junimii" },
  { label: "Strada Grigore Ureche" },
  { label: "Strada Florilor" },
  { label: "Strada Chimiștilor" },
  { label: "Strada Alexandru cel Bun" },
  { label: "Strada Mihail Sadoveanu" },
  { label: "Strada Timișoara" },
  { label: "Strada Hîrtoape" },
  { label: "Strada Alexei Mateevici" },
  { label: "Strada Bisericii" },
  { label: "Strada Nicolae Testemițanu" },
  { label: "Strada Alexandru Donici" },
  { label: "Strada Podgorenilor" },
  { label: "Strada Dealul Morilor" },
  { label: "Strada Decebal" },
  { label: "Stradela 3 Vovințeni" },
  { label: "Stradela 2 Vovințeni" },
  { label: "Stradela 1 Vovințeni" },
  { label: "Strada Dumbrăvii" },
  { label: "Strada Teiului" },
  { label: "Strada Stejarului" },
  { label: "Strada Valea Babei" },
  { label: "Strada Păcii" },
  { label: "Strada Calea Unirii" },
  { label: "Stradela 1 Cișmelelor" },
  { label: "Stradela 2 Cișmelelor" },
  { label: "Strada Balcani" },
  { label: "Stradela 3 Calea Unirii" },
  { label: "Stradela 4 Balcani" },
  { label: "Strada Făterilor" },
  { label: "Stradela 3 Balcani" },
  { label: "Stradela Renașterii" },
  { label: "Strada Barbu Lăutaru" },
  { label: "Stradela Iași" },
  { label: "Strada Cantinei" },
  { label: "Stradela 5 Balcani" },
  { label: "Stradela 2 Sfîntul Gheorghe" },
  { label: "Strada Toma Alimoș" },
  { label: "Stradela Hotin" },
  { label: "Stradela 1 Balcani" },
  { label: "Stradela 2 Rezistenței" },
  { label: "Șoseaua Hîncești" },
  { label: "Stradela 1 Livezilor" },
  { label: "Stradela Alexandru cel Bun" },
  { label: "Stradela 2 Balcani" },
  { label: "Stradela Dacilor" },
  { label: "Stradela 2 Livezilor" },
  { label: "Stradela 2 Petru Movilă" },
  { label: "Stradela Nicolae Milescu Spătarul" },
  { label: "Stradela 1 Ștefan-Vodă" },
  { label: "Stradela Alexei Mateevici" },
  { label: "Strada Rezistenței" },
  { label: "Strada Renașterii" },
  { label: "Stradela Tudor Vladimirescu" },
  { label: "Strada Ruhuleanca" },
  { label: "Stradela 1 Rezistenței" },
  { label: "Stradela Rediul Mic" },
  { label: "Strada Atelierilor" },
  { label: "Stradela 3 Plopilor" },
  { label: "Stradela Nicolae Dimo" },
  { label: "Stradela Toma Alimoș" },
  { label: "Strada Plopilor" },
  { label: "Stradela Caucaz" },
  { label: "Stradela Mihai Eminescu" },
  { label: "Stradela 2 Calea Unirii" },
  { label: "Stradela 1 Plopilor" },
  { label: "Stradela Codrilor" },
  { label: "Stradela 1 Nicolae Testemițanu" },
  { label: "Stradela 2 Plopilor" },
  { label: "Strada Mircești" },
  { label: "Strada Eremei Stratan" },
  { label: "Stradela Sfîntul Gheorghe" },
  { label: "Stradela Izvoarelor" },
  { label: "Strada Boris Zavatin" },
  { label: "Strada Budăi" },
  { label: "Strada Voluntarilor" },
  { label: "Stradela 1 Calea Unirii" },
  { label: "Strada Vovințeni" },
  { label: "Stradela Bisericii" },
  { label: "Strada Alexandr Orlov" },
  { label: "Strada Mihail Odatiuc" },
  { label: "Strada Sfîntul Andrei" },
  { label: "Strada Maria Cebotari" },
  { label: "Stradela 2 Ștefan-Vodă" },
  { label: "Stradela Rediul Mare" },
  { label: "Strada Tineretului" },
  { label: "Stradela 1 Petru Movilă" },
  { label: "Stradela 1 Tineretului" },
  { label: "Stradela 2 Tineretului" },
  { label: "Stradela 3 Tineretului" },
  { label: "Stradela 4 Tineretului" },
  { label: "Stradela 5 Tineretului" },
  { label: "Stradela 1 Tudor Vladimirescu" },
  { label: "Stradela 2 Tudor Vladimirescu" },
  { label: "Stradela 7 Tineretului" },
  { label: "Stradela 6 Tineretului" },
  { label: "Strada Dealul Buiucanilor" },
  { label: "Stradela 4 Vovințeni" },
  { label: "Stradela 8 Tineretului" },
  { label: "Stradela 1 Codrilor" },
  { label: "Stradela 9 Tineretului" },
  { label: "Strada Trandafirilor" },
  { label: "Stradela Trandafirilor" },
  { label: "Strada Nicolae Sulac" },
  { label: "Strada Cireșului" },
  { label: "Stradela 2 Nicolae Testemițanu" },
  { label: "Stradela 3 Nicolae Testemițanu" },
  { label: "Stradela 4 Nicolae Testemițanu" },
  { label: "Strada Dumbrava" },
  { label: "Strada Zelenoaia" },
  { label: "Strada Emil Loteanu" },
  { label: "Stradela 10 Ivan Miciurin" },
  { label: "Stradela 9 Ivan Miciurin" },
  { label: "Stradela 8 Ivan Miciurin" },
  { label: "Stradela 7 Ivan Miciurin" },
  { label: "Stradela 6 Ivan Miciurin" },
  { label: "Stradela 5 Ivan Miciurin" },
  { label: "Stradela 4 Ivan Miciurin" },
  { label: "Stradela 3 Ivan Miciurin" },
  { label: "Stradela 2 Ivan Miciurin" },
  { label: "Stradela 1 Ivan Miciurin" },
  { label: "Strada Ivan Miciurin" },
  { label: "Strada Adrian Păunescu" },
  { label: "Strada Mitropolit Gurie Grosu" },
  { label: "Strada Ștefan Ciobanu" },
  { label: "Strada Grigore Grigoriu" },
  { label: "Strada Independenței" },
  { label: "Stradela Păcii" },
  { label: "Strada Basarabia" },
  { label: "Strada Drumul Morilor" },
  { label: "Strada Liviu Deleanu" },
];
export const stauceniStreat = [
  { label: "Strada Ştefan cel Mare" },
  { label: "Strada Mitropolit Varlaam" },
  { label: "Strada Grigore Ureche" },
  { label: "Strada Mihai Eminescu" },
  { label: "Strada Nicolae Iorga" },
  { label: "Strada Florilor" },
  { label: "Strada Valea Ungurului" },
  { label: "Strada Teilor" },
  { label: "Strada Ștefan Vodă" },
  { label: "Strada Calea Orheiului" },
  { label: "Strada Alexandru cel Bun" },
  { label: "Strada Trandafirilor" },
  { label: "Strada Livezilor" },
  { label: "Strada Viilor" },
  { label: "Strada Frunzei" },
  { label: "Strada Nucarilor" },
  { label: "Strada Pădurii" },
  { label: "Strada Poștei" },
  { label: "Strada Prieteniei" },
  { label: "Strada Gării" },
  { label: "Strada Izvorului" },
  { label: "Strada Miorița" },
  { label: "Strada Orheiului" },
  { label: "Strada Primăverii" },
  { label: "Strada Salcâmilor" },
  { label: "Strada Speranței" },
  { label: "Strada Tineretului" },
  { label: "Strada Tudor Vladimirescu" },
];

export const chisinauStreat = [
  { label: "Bulevardul Constantin Negruzzi" },
  { label: "Bulevardul Cuza-Vodă" },
  { label: "Bulevardul Dacia" },
  { label: "Bulevardul Decebal" },
  { label: "Bulevardul Dimitrie Cantemir" },
  { label: "Bulevardul Grigore Vieru" },
  { label: "Bulevardul Iuri Gagarin" },
  { label: "Bulevardul Mircea cel Bătrîn" },
  { label: "Bulevardul Moscova" },
  { label: "Bulevardul Renașterii Naționale" },
  { label: "Bulevardul Ștefan cel Mare și Sfînt" },
  { label: "Bulevardul Traian" },
  { label: "Piața Dimitrie Cantemir" },
  { label: "Piața Gării" },
  { label: "Piața Iulius Cezar" },
  { label: "Piața Marea Adunare Națională" },
  { label: "Piața Unirii Principatelor" },
  { label: "Șoseaua Balcani" },
  { label: "Strada 27 Martie 1918" },
  { label: "Strada 31 August 1989" },
  { label: "Strada 8 Martie" },
  { label: "Strada Academician Andrei Saharov" },
  { label: "Strada Academician Eugen Coșeriu" },
  { label: "Strada Academician Iachim Grosul" },
  { label: "Strada Academician Natalia Gheorghiu" },
  { label: "Strada Academician Nicolae Corlăteanu" },
  { label: "Strada Academician Sergiu Rădăuțanu" },
  { label: "Strada Academician Silviu Berejan" },
  { label: "Strada Academiei" },
  { label: "Strada Aerodromului" },
  { label: "Strada Aeroport" },
  { label: "Strada Agnesa Roșca" },
  { label: "Strada Alba Iulia" },
  { label: "Strada Albăstrele" },
  { label: "Strada Albișoara" },
  { label: "Strada Albița" },
  { label: "Strada Alcedar" },
  { label: "Strada Alecu Donici" },
  { label: "Strada Alecu Russo" },
  { label: "Strada Aleea Gării" },
  { label: "Strada Aleksandr Pușkin" },
  { label: "Strada Alexandru Bernardazzi" },
  { label: "Strada Alexandru Boldur" },
  { label: "Strada Alexandru Botezatu" },
  { label: "Strada Alexandru cel Bun" },
  { label: "Strada Alexandru Cosmescu" },
  { label: "Strada Alexandru Cristea" },
  { label: "Strada Alexandru Hâjdeu" },
  { label: "Strada Alexandru Lăpușneanu" },
  { label: "Strada Alexandru Marinescu" },
  { label: "Strada Alexandru Negru-Vodă" },
  { label: "Strada Alexandru Plămădeală" },
  { label: "Strada Alexandru Vlăhuță" },
  { label: "Strada Alexandru Xenopol" },
  { label: "Strada Alexei Belski" },
  { label: "Strada Alexei Mateevici" },
  { label: "Strada Alexei Șciusev" },
  { label: "Strada Aluniș" },
  { label: "Strada Anatol Corobceanu" },
  { label: "Strada Anatol Popovici" },
  { label: "Strada Andrei Ciurunga" },
  { label: "Strada Andrei Doga" },
  { label: "Strada Andrei Izbaș" },
  { label: "Strada Andrei Lupan" },
  { label: "Strada Andrei Mureșanu" },
  { label: "Strada Andrei Tupolev" },
  { label: "Strada Angela Păduraru" },
  { label: "Strada Ankara" },
  { label: "Strada Anton Ablov" },
  { label: "Strada Anton Crihan" },
  { label: "Strada Anton Pann" },
  { label: "Strada Arborilor" },
  { label: "Strada Arheolog Ion Casian Suruceanu" },
  { label: "Strada Arionești" },
  { label: "Strada Armenească" },
  { label: "Strada Armoniei" },
  { label: "Strada Aron Pumnul" },
  { label: "Strada Arțarului" },
  { label: "Așhabad" },
  { label: "Strada Astronauților" },
  { label: "Strada Astronom Nicolae Donici" },
  { label: "Strada Aurel David" },
  { label: "Strada Aurel Vlaicu" },
  { label: "Strada Aviatorilor" },
  { label: "Strada Avicenna" },
  { label: "Strada Avocat Eugenia Crușevan" },
  { label: "Strada Avram Iancu" },
  { label: "Strada Bacău" },
  { label: "Strada Băcioii Noi" },
  { label: "Strada Baku" },
  { label: "Strada Bălănescu" },
  { label: "Strada Băltagi" },
  { label: "Strada Bălți" },
  { label: "Strada Banatului" },
  { label: "Strada Barbu Lăutaru" },
  { label: "Strada Bariera Orhei" },
  { label: "Strada Bariera Sculeni" },
  { label: "Strada Basarabilor" },
  { label: "Strada Bazinului" },
  { label: "Strada Belgrad" },
  { label: "Strada Belșugului" },
  { label: "Strada Bisericii" },
  { label: "Strada Bogdan Petriceicu Hasdeu" },
  { label: "Strada Bogdan Voievod" },
  { label: "Strada Botanica Veche" },
  { label: "Strada Boteaza" },
  { label: "Strada Brăila" },
  { label: "Strada Braniștii" },
  { label: "Strada Bucovinei" },
  { label: "Strada București" },
  { label: "Strada Bucuriei" },
  { label: "Strada Budăi" },
  { label: "Strada Budești" },
  { label: "Strada Bugeacului" },
  { label: "Strada Buiucani" },
  { label: "Strada Bujorilor" },
  { label: "Strada Bulboaca" },
  { label: "Strada Bulbocica" },
  { label: "Strada Bulgară" },
  { label: "Strada Buna Vestire" },
  { label: "Strada Burebista" },
  { label: "Strada Busuiocești" },
  { label: "Strada Butuceni" },
  { label: "Strada Butucului" },
  { label: "Strada Cahul" },
  { label: "Strada Caișilor" },
  { label: "Strada Călărași" },
  { label: "Strada Călătorilor" },
  { label: "Calea Basarabiei" },
  { label: "Calea Dacilor" },
  { label: "Calea Ghidighici" },
  { label: "Calea Ieșilor" },
  { label: "Calea Moșilor" },
  { label: "Calea Orheiului" },
  { label: "Călugăreni" },
  { label: "Călușari" },
  { label: "Strada Camenița" },
  { label: "Strada Cantonului" },
  { label: "Strada Căpriana" },
  { label: "Strada Capricorn" },
  { label: "Strada Cărămidarilor" },
  { label: "Strada Cărăușilor" },
  { label: "Strada Cărbunari" },
  { label: "Strada Carierei" },
  { label: "Strada Caucaz" },
  { label: "Strada Căușeni" },
  { label: "Strada Cernăuți" },
  { label: "Strada Cernica" },
  { label: "Strada Cetatea Albă" },
  { label: "Strada Cetatea Chilia" },
  { label: "Strada Cetinii" },
  { label: "Strada Ceucari" },
  { label: "Strada Chițcani" },
  { label: "Strada Cimbrului" },
  { label: "Strada Ciocana" },
  { label: "Strada Ciocîrliei" },
  { label: "Strada Cioricești" },
  { label: "Strada Ciprian Porumbescu" },
  { label: "Strada Cireșilor" },
  { label: "Strada Cișmele" },
  { label: "Strada Ciuflea" },
  { label: "Strada Cneaz Ivan Mazepa" },
  { label: "Strada Colina Verde" },
  { label: "Strada Columna" },
  { label: "Strada Colonița" },
  { label: "Strada Combatantului" },
  { label: "Strada Comandant Manoli" },
  { label: "Strada Comuna din Paris" },
  { label: "Strada Constantin Vîrnav" },
  { label: "Strada Contemporanul" },
  { label: "Strada Constantin Brâncoveanu" },
  { label: "Strada Constantin Brâncuși" },
  { label: "Strada Constantin Stere" },
  { label: "Strada Constantin Tănase" },
  { label: "Strada Constantin Vîrnav" },
  { label: "Strada Corăbiei" },
  { label: "Strada Cornești" },
  { label: "Strada Cornului" },
  { label: "Strada Costiujeni" },
  { label: "Strada Coșbuc" },
  { label: "Strada Cotovschi" },
  { label: "Strada Cotului" },
  { label: "Strada Cramei" },
  { label: "Strada Creangă Ion" },
  { label: "Strada Crinilor" },
  { label: "Strada Cristofor Columb" },
  { label: "Strada Crizantemelor" },
  { label: "Strada Ctin Ivanov" },
  { label: "Strada Ctin Stere" },
  { label: "Strada Cucorilor" },
  { label: "Strada Cucului" },
  { label: "Strada Curcubeului" },
  { label: "Strada Curmalilor" },
  { label: "Strada Cuzmenco" },
  { label: "Strada Dacia" },
  { label: "Strada Dancuța" },
  { label: "Strada Danubiu" },
  { label: "Strada Dănuțeni" },
  { label: "Strada Dealu Albastru" },
  { label: "Strada Decebal" },
  { label: "Strada Decebal-2" },
  { label: "Strada Deleanu" },
  { label: "Strada Delia" },
  { label: "Strada Dendrarium" },
  { label: "Strada Detroit" },
  { label: "Strada Dimo" },
  { label: "Strada Doina" },
  { label: "Strada Dokuceaev" },
  { label: "Strada Domnița Ruxandra" },
  { label: "Strada Domnitorilor" },
  { label: "Strada Donici" },
  { label: "Strada Dorobanților" },
  { label: "Strada Dovleacului" },
  { label: "Strada Dokuceaev" },
  { label: "Strada Drăgan Nicolae" },
  { label: "Strada Drumul Băcioilor" },
  { label: "Strada Drumul Crucii" },
  { label: "Strada Drumul Schinoasei" },
  { label: "Strada Dumbrava Roșie" },
  { label: "Strada Dumitru Matcovschi" },
  { label: "Strada Durlești" },
  { label: "Strada Ecaterina Teodoroiu" },
  { label: "Strada Ede Dessewffy" },
  { label: "Strada Edineț" },
  { label: "Strada Eduard Amvrosievici" },
  { label: "Strada Eftimie Murgu" },
  { label: "Strada Eliza Opran" },
  { label: "Strada Elena Alistar" },
  { label: "Strada Elena Doamna" },
  { label: "Strada Elena Sârbu" },
  { label: "Strada Elena Văcărescu" },
  { label: "Strada Eliberării" },
  { label: "Strada Eminescu Mihai" },
  { label: "Strada Energia" },
  { label: "Strada Eugen Coca" },
  { label: "Strada Eugen Doga" },
  { label: "Strada Eugen Coca" },
  { label: "Strada Eudoxiu Hurmuzachi" },
  { label: "Strada Evanghelist Luca" },
  { label: "Strada Făgăraș" },
  { label: "Strada Fălticeni" },
  { label: "Strada Fantanița Rece" },
  { label: "Strada Faptelor" },
  { label: "Strada Făurari" },
  { label: "Strada Fagurelui" },
  { label: "Strada Feldman Mihail" },
  { label: "Strada Ferdinand I" },
  { label: "Strada Feroviară" },
  { label: "Strada Filantropia" },
  { label: "Strada Filimon Balțan" },
  { label: "Strada Filipeni" },
  { label: "Strada Filipescu Ctin" },
  { label: "Strada Fiorella" },
  { label: "Strada Florăriei" },
  { label: "Strada Florilor" },
  { label: "Strada Frunzei" },
  { label: "Strada Frunzei Mici" },
  { label: "Strada Fuiorului" },
  { label: "Strada Fundăturii" },
  { label: "Strada Furnicilor" },
  { label: "Strada Găgăuzia" },
  { label: "Strada Gălăiești" },
  { label: "Strada Gălănești" },
  { label: "Strada Găleata" },
  { label: "Strada Gălești" },
  { label: "Strada Gălileu" },
  { label: "Strada Ganea" },
  { label: "Strada Ganeș" },
  { label: "Strada Gărboveț" },
  { label: "Strada Gărceni" },
  { label: "Strada Gărgălău" },
  { label: "Strada Gheorghe Țăranu" },
  { label: "Strada Gheorghe Asachi" },
  { label: "Strada Gheorghe Cibotaru" },
  { label: "Strada Gheorghe Codreanu" },
  { label: "Strada Gheorghe Dobrea" },
  { label: "Strada Gheorghe Ghimpu" },
  { label: "Strada Gheorghe Ivan" },
  { label: "Strada Gheorghe Marinescu" },
  { label: "Strada Gheorghe Pîntea" },
  { label: "Strada Gheorghe Petrașcu" },
  { label: "Strada Gheorghe Tofan" },
  { label: "Strada Gheorghe Tudor" },
  { label: "Strada Gheorghe Ureche" },
  { label: "Strada Gheorghe Ursu" },
  { label: "Strada Ghilasa" },
  { label: "Strada Gheorghe Vrânceanu" },
  { label: "Strada Gheorghiu Ion" },
  { label: "Strada Ghiocel" },
  { label: "Strada Gîrlești" },
  { label: "Strada Gîrleștii Noi" },
  { label: "Strada Gîrnești" },
  { label: "Strada Gîtul Iepei" },
  { label: "Strada Glavanovca" },
  { label: "Strada Glavanovca Veche" },
  { label: "Strada Glăvănești" },
  { label: "Strada Glie" },
  { label: "Strada Glieci" },
  { label: "Strada Gloriei" },
  { label: "Strada Gogu Viu" },
  { label: "Strada Gogolev" },
  { label: "Strada Golgota" },
  { label: "Strada Gornișcev" },
  { label: "Strada Grădinari" },
  { label: "Strada Grădina Botanică" },
  { label: "Strada Grădina București" },
  { label: "Strada Grădina Copiilor" },
  { label: "Strada Grădina de Vară" },
  { label: "Strada Grădina Publică" },
  { label: "Strada Grădina Viilor" },
  { label: "Strada Grădinilor" },
  { label: "Strada Grădinilor Noi" },
  { label: "Strada Grădinilor Veche" },
  { label: "Strada Grea" },
  { label: "Strada Greblei" },
  { label: "Strada Greco-Catolică" },
  { label: "Strada Gregorașe" },
  { label: "Strada Gregoriada" },
  { label: "Strada Greuceanu" },
  { label: "Strada Grigore Alexandrescu" },
  { label: "Strada Grigore Antipa" },
  { label: "Strada Grigore Bălan" },
  { label: "Strada Grigore Cazacliu" },
  { label: "Strada Grigore Dima" },
  { label: "Strada Grigore Ilisei" },
  { label: "Strada Grigore Moisil" },
  { label: "Strada Grigore Moșanu" },
  { label: "Strada Grigore Munteanu" },
  { label: "Strada Grigore Ureche" },
  { label: "Strada Grigore Vieru" },
  { label: "Strada Groapa Boldurului" },
  { label: "Strada Grozavești" },
  { label: "Strada Grupului de Aviatori" },
  { label: "Strada Grupului de Foc" },
  { label: "Strada Grupului de Pompieri" },
  { label: "Strada Grupului de Sărbători" },
  { label: "Strada Grupului Tinerilor" },
  { label: "Strada Grupul Școlar" },
  { label: "Strada Grupeț" },
  { label: "Strada Grus" },
  { label: "Strada Grusnii" },
  { label: "Strada Gruzia" },
  { label: "Strada Gruzde" },
  { label: "Strada Gura Bacului" },
  { label: "Strada Gura Crăciunei" },
  { label: "Strada Gura Râului" },
  { label: "Strada Gura Satului" },
  { label: "Strada Gura Văii" },
  { label: "Strada Gurei Iepei" },
  { label: "Strada Haga" },
  { label: "Strada Hâjdeu" },
  { label: "Strada Hâjdău" },
  { label: "Strada Halatz" },
  { label: "Strada Hălești" },
  { label: "Strada Hălmăjelor" },
  { label: "Strada Hâncești" },
  { label: "Strada Haralampie" },
  { label: "Strada Haralampiescu" },
  { label: "Strada Hareții" },
  { label: "Strada Haretului" },
  { label: "Strada Harman" },
  { label: "Strada Hărtopului" },
  { label: "Strada Hasdeu" },
  { label: "Strada Havîrna" },
  { label: "Strada Heliade Rădulescu" },
  { label: "Strada Heltei" },
  { label: "Strada Hâncul" },
  { label: "Strada Herculane" },
  { label: "Strada Herța" },
  { label: "Strada Herțeni" },
  { label: "Strada Herțenstein" },
  { label: "Strada Higrometrei" },
  { label: "Strada Himalaya" },
  { label: "Strada Hincu" },
  { label: "Strada Hipnotizatorilor" },
  { label: "Strada Hipodromului" },
  { label: "Strada Hîncul" },
  { label: "Strada Hîrtopului" },
  { label: "Strada Hofigal" },
  { label: "Strada Horez" },
  { label: "Strada Horezului" },
  { label: "Strada Horia" },
  { label: "Strada Hornului" },
  { label: "Strada Horea" },
  { label: "Strada Horia Cloșca" },
  { label: "Strada Horia Ionescu" },
  { label: "Strada Horoscopului" },
  { label: "Strada Hosdăjeni" },
  { label: "Strada Hotin" },
  { label: "Strada Hotoveni" },
  { label: "Strada Hramului" },
  { label: "Strada Hrisovului" },
  { label: "Strada Hristofi" },
];
